import torch
import numpy as np
import pandas as pd

from sklearn.metrics import mean_squared_error, mean_absolute_error
from pipeline import TimeSeriesClassification, TimeSeriesRegression, TabularClassification, TabularRegression
from trainer import Trainer
from visualiser import Visualiser
from analyser import Analyser

import data as _data

INTERVAL = 1
UNIT = 'H'

SEQ_LEN = 24
def _extract_numpy_from_loader(loader):
    """Helper function to convert a DataLoader back to NumPy arrays."""
    all_X, all_y = [], []
    for _, X_tensor, y_tensor, *_ in loader:
        all_X.append(X_tensor.cpu().numpy())
        all_y.append(y_tensor.cpu().numpy())
    
    X_arr = np.concatenate(all_X)
    # Reshape if data is sequential, as XGBoost expects 2D input
    if X_arr.ndim > 2:
        X_arr = X_arr.reshape(X_arr.shape[0], -1)
        
    return X_arr, np.concatenate(all_y)

def prepare_data() -> Analyser:
    print("--- Loading and Processing Raw Data ---")
    
    # Load the data
    data = _data.load()
    visualiser = Visualiser(data)
    analyser = Analyser(data)

    # Clean and aggregate
    analyser.process_outliers()
    analyser.aggregate.time_data(interval=INTERVAL, unit=UNIT, inplace=True)
    analyser.aggregate.activity(interval=INTERVAL, unit=UNIT, inplace=True)
    analyser.aggregate.communication_events(interval=INTERVAL, unit=UNIT, inplace=True)
    analyser.aggregate.reported_data(interval=INTERVAL, unit=UNIT, inplace=True)

    analyser.apply_scaling(inplace=True) # Scale before imputation to prevent data leakage from imputed values

    # Save intermediate state
    analyser.data.to_csv('data/aggregated_data.csv', index=False)
    
    # Impute missing values
    # print("Running imputation...")
    # analyser.impute(delete=False, catsi=True, epochs=1)
    # analyser.data.to_csv('data/aggregated_data_after_impute.csv', index=False)

    # Quick diagnostic check
    missing_data = analyser.data.isna().any().sum()
    visualiser.heatmap_missing_values_per_id(save=True)
    print(f"Columns with missing data after imputation: {missing_data}")
    
    return analyser

def evaluate_daily_assignment_loss(model, dataloader, device='cpu'):
    """
    Computes the loss on the Daily Average Mood, satisfying the assignment requirement.
    
    Args:
        model: The trained PyTorch model.
        dataloader: The DataLoader containing the test/validation set (yielding 4 tensors).
        device: 'cpu' or 'cuda'/'mps'.
        
    Returns:
        daily_df: A Pandas DataFrame containing the grouped daily predictions and actuals.
        mse: Mean Squared Error of the daily averages.
        mae: Mean Absolute Error of the daily averages.
    """
    model.eval()
    all_ids, all_times, all_preds, all_actuals = [], [], [], []
    
    print("\n--- Evaluating Predictions for Daily Aggregation ---")
    
    with torch.no_grad():
        for batch in dataloader:
            # Explicitly unpack all 4 tensors generated by our updated pipeline
            id_tensor, X_tensor, y_tensor, time_tensor = [b.to(device) for b in batch]
            
            # Forward pass
            outputs = model(id_tensor, X_tensor)
            
            # Move everything to CPU, detach from graph, and flatten into standard Python lists
            all_ids.extend(id_tensor.cpu().numpy())
            all_times.extend(time_tensor.cpu().numpy())
            all_preds.extend(outputs.cpu().numpy().flatten())
            all_actuals.extend(y_tensor.cpu().numpy().flatten())
            
    # 1. Build a raw Pandas DataFrame from the hourly predictions
    df = pd.DataFrame({
        'id': all_ids,
        'timestamp': all_times,
        'predicted_mood': all_preds,
        'actual_mood': all_actuals
    })
    
    # 2. Convert Unix timestamps (seconds) back to standard Calendar Dates
    df['date'] = pd.to_datetime(df['timestamp'], unit='s').dt.date
    
    # 3. Group by ID and Date, then calculate the mean for both predictions and actuals
    daily_df = df.groupby(['id', 'date']).agg({
        'predicted_mood': 'mean',
        'actual_mood': 'mean'
    }).reset_index()
    
    # 4. Compute Final Assignment Metrics on the Daily Averages
    mse = mean_squared_error(daily_df['actual_mood'], daily_df['predicted_mood'])
    mae = mean_absolute_error(daily_df['actual_mood'], daily_df['predicted_mood'])
    
    # 5. Print a clean, formatted report
    print("\n" + "="*45)
    print("🎯 FINAL DAILY ASSIGNMENT METRICS")
    print("="*45)
    print(f"Total Hourly Data Points: {len(df):,}")
    print(f"Total Daily Aggregations: {len(daily_df):,}")
    print("-" * 45)
    print(f"Daily Mean Squared Error (MSE):  {mse:.4f}")
    print(f"Daily Mean Absolute Error (MAE): {mae:.4f}")
    print("="*45)
    
    return daily_df, mse, mae

def train_classification_model(analyser):
    print("\n--- Initializing Machine Learning Pipeline ---")
    
    pipeline = TimeSeriesClassification(analyser, seq_len=SEQ_LEN, num_bins=5, batch_size=16)
    train_loader, val_loader, test_loader = pipeline.get_dataloaders()

    # FIX: Unpack 4 items now since our dataloader yields (IDs, X, y, Time)
    sample_id, sample_X, sample_y, sample_time = next(iter(train_loader))
    batch, seq_len, num_features = sample_X.shape
    
    print(f"Detected {num_features} input features.")

    # 2. Instantiate the Model
    model = pipeline.build_model(hidden_dim=64, embed_dim=6, dropout_rate=0.5)

    # 3. Define Optimizer and Loss
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-3)
    criterion = torch.nn.CrossEntropyLoss()

    # 4. Train the Model
    trainer = Trainer(model, optimizer, criterion, task_type='classification')
    trainer.fit(train_loader, val_loader=val_loader, num_epochs=300)
    
    # Optional: Run a final pass on the test set
    print("\n--- Running Final Test Set Evaluation ---")
    test_metrics = trainer._validate_epoch(test_loader)
    print(f"Test Accuracy: {test_metrics.get('acc', 0.0):.1%}")


def train_regression_model(analyser):
    print("\n--- Initializing Machine Learning Pipeline ---")
    
    pipeline = TimeSeriesRegression(analyser, seq_len=SEQ_LEN, batch_size=16)
    train_loader, val_loader, test_loader = pipeline.get_dataloaders()

    # FIX: Unpack 4 items now
    sample_id, sample_X, sample_y, sample_time = next(iter(train_loader))
    batch, seq_len, num_features = sample_X.shape
    
    print(f"Detected {num_features} input features.")

    # 2. Instantiate the Model
    model = pipeline.build_model(hidden_dim=64, embed_dim=6, dropout_rate=0.5)

    # 3. Define Optimizer and Loss
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-3)
    criterion = torch.nn.MSELoss()

    # 4. Train the Model on Hourly Data
    trainer = Trainer(model, optimizer, criterion, task_type='regression')
    trainer.fit(train_loader, val_loader=val_loader, num_epochs=300)

    # ---------------------------------------------------------
    # 5. ASSIGNMENT EVALUATION (Daily Average)
    # Run this strictly on the Test Loader to prove generalization!
    # ---------------------------------------------------------
    results_df, final_mse, final_mae = evaluate_daily_assignment_loss(
        model=trainer.model, 
        dataloader=test_loader, 
        device=trainer.device
    )
    
    # Save the final predictions dataframe to a CSV for your report
    save_path = "final_daily_predictions.csv"
    results_df.to_csv(save_path, index=False)
    print(f"Saved exact daily predictions to: '{save_path}'")


def walk_forward_train(analyser, tabular=False):
    """ 
    Train a model using walk-forward validation. 
    Simulates real-world scenario of training on past data and validating on future data.
    """
    # 1. Setup Pipeline
    # Using a shorter seq_len as discussed to preserve data points
    if tabular:
        pipeline = TabularClassification(analyser, lookahead = 1, num_bins=5, batch_size=16)
    else:
        pipeline = TimeSeriesClassification(analyser, seq_len=24, num_bins=5, batch_size=16)
    
    # get_walk_forward_loaders returns (folds, test_loader)
    # Each fold is a tuple: (train_loader, val_loader)
    folds, test_loader = pipeline.get_walk_forward_loaders(n_splits=5, gap=5, test_ratio=0.15)

    # 2. Walk-Forward Loop
    fold_results = []
    trained_model = None  # To keep track of the most recently trained model for final evaluation

    for fold_idx, (train_loader, val_loader) in enumerate(folds):
        print(f"\n" + "="*30)
        print(f"🚀 STARTING FOLD {fold_idx + 1}/{len(folds)}")
        print(f"="*30)
        
        if tabular:
            model = pipeline.build_xgboost_model()
            X_train, y_train = _extract_numpy_from_loader(train_loader)
            X_val, y_val = _extract_numpy_from_loader(val_loader)
            print(f"Fitting XGBoost on Fold {X_train.shape[0]} training samples...")
            model.fit(X_train, y_train, eval_set=[(X_val, y_val)], early_stopping_rounds=10, verbose=False)
            
            # Evaluate on validation set
            val_preds = model.predict(X_val)
            val_acc = (val_preds == y_val).mean()
            fold_results.append({'acc': val_acc})
            print(f"Fold {fold_idx + 1} Validation Accuracy: {val_acc:.2%}")
            trained_model = model  # Update the most recently trained model for final test evaluation
        else:
            # DESIGN CHOICE: Re-instantiate model/optimizer for every fold.
            # This ensures each fold is an independent test of the training strategy.
            model = pipeline.build_model(hidden_dim=32, embed_dim=5, dropout_rate=0.5)
            
            optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)
            criterion = torch.nn.CrossEntropyLoss()

            # Initialize Trainer
            trainer = Trainer(model, optimizer, criterion, task_type='classification')

            # Fit on this fold's specific data
            trainer.fit(train_loader=train_loader, val_loader=val_loader, num_epochs=50)
            
            # Optionally: Evaluate on val_loader one last time to save results
            val_metrics = trainer._validate_epoch(val_loader)
            fold_results.append(val_metrics)
            trained_model = trainer 

    # 3. Final Evaluation on the held-out Test Set
    # We use the trainer from the VERY LAST fold to evaluate the test set,
    # as it has been trained on the most recent data.
    print("\n" + "X"*40)
    print("      FINAL WALK-FORWARD TEST")
    print("X"*40)

    if tabular:
        X_test, y_test = _extract_numpy_from_loader(test_loader)
        test_preds = trained_model.predict(X_test)
        test_acc = (test_preds == y_test).mean()
        test_metrics = {'acc': test_acc}
    else:
        test_metrics = trainer._validate_epoch(test_loader)
    
    avg_fold_acc = sum(f['acc'] for f in fold_results) / len(fold_results)
    
    print(f"Average Fold Validation Accuracy: {avg_fold_acc:.2%}")
    print(f"Final Held-out Test Accuracy:    {test_metrics.get('acc', 0.0):.2%}")

    return fold_results, test_metrics

def main():
    analyser = prepare_data()
    walk_forward_train(analyser)
    # train_regression_model(analyser)

if __name__ == "__main__":
    main()
